// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9K-VNPwUqSPiZleKD5_VjuXudsg89sGA',
    appId: '1:1097120590111:web:778e72703a27dcfc25682a',
    messagingSenderId: '1097120590111',
    projectId: 'agriculture-f3479',
    authDomain: 'agriculture-f3479.firebaseapp.com',
    storageBucket: 'agriculture-f3479.appspot.com',
    measurementId: 'G-H0L4N4B5TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwaBVZPVgUmNtvOGWeGAa3M2neuMqHNqk',
    appId: '1:1097120590111:android:db2976d271cde26f25682a',
    messagingSenderId: '1097120590111',
    projectId: 'agriculture-f3479',
    storageBucket: 'agriculture-f3479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR5k5aJ_7p33M8O62lm39_xV2NwgO9GCQ',
    appId: '1:1097120590111:ios:e8f5d9712778d3db25682a',
    messagingSenderId: '1097120590111',
    projectId: 'agriculture-f3479',
    storageBucket: 'agriculture-f3479.appspot.com',
    androidClientId: '1097120590111-h56fptp3rsc7gib82iobotda1dgttev1.apps.googleusercontent.com',
    iosClientId: '1097120590111-cq9l8uu0pac4dd0j0hqthcrl8q8cj8bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR5k5aJ_7p33M8O62lm39_xV2NwgO9GCQ',
    appId: '1:1097120590111:ios:e8f5d9712778d3db25682a',
    messagingSenderId: '1097120590111',
    projectId: 'agriculture-f3479',
    storageBucket: 'agriculture-f3479.appspot.com',
    androidClientId: '1097120590111-h56fptp3rsc7gib82iobotda1dgttev1.apps.googleusercontent.com',
    iosClientId: '1097120590111-cq9l8uu0pac4dd0j0hqthcrl8q8cj8bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9K-VNPwUqSPiZleKD5_VjuXudsg89sGA',
    appId: '1:1097120590111:web:3dc142a8c5cef2ca25682a',
    messagingSenderId: '1097120590111',
    projectId: 'agriculture-f3479',
    authDomain: 'agriculture-f3479.firebaseapp.com',
    storageBucket: 'agriculture-f3479.appspot.com',
    measurementId: 'G-FLSW4H0GQ0',
  );

}